default: &DEFAULT
  # model
  model: 'ffn'   # feedfoward
  num_data_workers: 6
  depth: 5  
  in_dim: 2
  out_dim: 1
  hidden_dim: 50 # hidden dim
  # system
  system: 'advection' # advection, rd, poisson, posiadv
  ic: 'sin(x)' # initial condition (sin(x) or gauss) for time-dependentproblems
  beta: 1      # advection velocity
  source: 0    # source
  diff_coef_freq: 0    # for heterogeneous diffusion: see utils/misc_utils for the different diffusion/velocity vals used
  diff_coef_scale: 1
  # data/domain
  L: '2pi'
  T: !!float 1.0
  nx: 256
  nt: 100
  n_col: 1000
  n_val: 30000
  # optimization
  loss_style: 'mean'  # mean or sum over all points
  loss_func: 'pinns'
  optimizer: 'lbfgs'  # lbfgs or adam
  scheduler: 'none'   # learning rate scheduler (none or cosine)
  bc_type: 'none'     # none is periodic, can also be dirichlet
  lr: !!float 1.0
  max_epochs: 5000
  max_iter: 1
  batch_size: 'none'
  patience: 10       # early stopper patience
  resample_schedule_T: 1000
  uniform_reg: 0.05
  sample_freq: 50
  reg: 1
  warmstart: 0
  res_momentum: 0
  kill_opt: !!bool True
  # misc
  log_to_screen: !!bool True  
  save_checkpoint: !!bool False
  seed: 0
  early_stop: !!bool True 
  plot_figs: !!bool False
  test_every_epoch: !!bool True
  vis_loss: !!bool False    # visualize loss landscape with pyhessian
  all_col_points: !!bool False
  mask: !!bool False
  init_weights: !!bool False
  resample: !!bool False
  use_grad_resample: !!bool False
  track_eigv: !!bool False
  enable_obs: !!bool False
  num_gauss: 1             # how many gaussians in the source function?
  diff_tensor_type: "iso"  # iso or aniso
  # Weights & Biases
  entity: 'pinns'
  project: 'PINNs'
  log_to_wandb: !!bool False

poisson: &poisson
  <<: *DEFAULT
  save_checkpoint: !!bool False
  all_col_points: !!bool False
  resample: !!bool True
  resample_schedule_T: 500
  sample_freq: 50
  max_epochs: 1000
  plot_figs: !!bool True
  loss_style: 'mean'
  system: 'poisson'
  force_std: !!float 0.1
  force_mean: !!float 0.5
  Lx: !!float 1.0
  Ly: !!float 1.0
  nx: 256
  ny: 256
  n_col: 1000

poisson-tc2:
  <<: *poisson
  save_checkpoint: !!bool False
  test_every_epoch: !!bool True
  use_grad_resample: !!bool False
  plot_figs: !!bool True
  bc_type: 'dirichlet'
  diff_tensor_type: "aniso"
  res_momentum: 0
  loss_style: 'mean'
  reg: 0.0001
  lr: 0.01
  max_epochs: 5000
  force_std: !!float 0.01
  resample_schedule_T: 1000
  sample_freq: 100
  resample: !!bool True
  all_col_points: !!bool False
  n_col: 1000
  n_val: 30000
  seed: 0
  uniform_reg: 0

poisson-tc1:
  <<: *poisson
  save_checkpoint: !!bool False
  test_every_epoch: !!bool True
  use_grad_resample: !!bool True
  plot_figs: !!bool True
  bc_type: 'dirichlet'
  diff_tensor_type: "aniso"
  res_momentum: 0.9
  loss_style: 'mean'
  reg: 0.0001
  lr: 1
  max_epochs: 5000
  force_std: !!float 0.1
  resample_schedule_T: 500
  sample_freq: 100
  resample: !!bool True
  all_col_points: !!bool False
  n_col: 1000
  seed: 0
  uniform_reg: 0

poisadv: &poisadv
  <<: *DEFAULT
  save_checkpoint: !!bool False
  test_every_epoch: !!bool True
  use_grad_resample: !!bool True
  bc_type: 'dirichlet'
  diff_tensor_type: "aniso"
  vel_type: "aniso"
  plot_figs: !!bool True
  system: 'poisadv'
  Lx: !!float 1.0
  Ly: !!float 1.0
  nx: 256
  ny: 256
  res_momentum: 0.9
  loss_style: 'mean'
  reg: 0.001
  lr: 0.1
  max_epochs: 5000
  force_std: !!float 0.01
  force_mean: !!float 0.5
  resample_schedule_T: 500
  sample_freq: 25
  resample: !!bool True
  all_col_points: !!bool False
  n_col: 500

poisadv-tc4:
  <<: *poisadv
  save_checkpoint: !!bool False
  test_every_epoch: !!bool True
  use_grad_resample: !!bool True
  bc_type: 'dirichlet'
  diff_tensor_type: "aniso"
  vel_type: "aniso"
  plot_figs: !!bool True
  res_momentum: 0.9
  loss_style: 'mean'
  reg: 0.0001
  lr: 1
  max_epochs: 5000
  resample_schedule_T: 1000
  sample_freq: 50
  resample: !!bool True
  all_col_points: !!bool False
  n_col: 1000
  uniform_reg: 0
  seed: 0

poisadv-tc3:
  <<: *poisadv
  save_checkpoint: !!bool False
  test_every_epoch: !!bool True
  use_grad_resample: !!bool True
  bc_type: 'dirichlet'
  diff_tensor_type: "aniso"
  vel_type: "aniso"
  plot_figs: !!bool True
  res_momentum: 0.9
  loss_style: 'mean'
  reg: 0.0001
  lr: 0.1
  force_std: !!float 0.1
  max_epochs: 5000
  resample_schedule_T: 500
  sample_freq: 100
  resample: !!bool True
  all_col_points: !!bool False
  n_col: 1000
  uniform_reg: 0
  seed: 0
  
